apiVersion: v1
kind: Service
metadata:
  name: writer-besu-lacchain
  labels:
    app: lacchain-writernode
  namespace: lacchain-network
spec:
  type: LoadBalancer
  selector:
    app: lacchain-writernode
  ports:
    - port: 60606
      targetPort: 60606
      protocol: TCP
      name: rlpx
    - port: 4545
      targetPort: 4545
      protocol: TCP
      name: json-rpc
    - port: 4546
      targetPort: 4546
      protocol: TCP
      name: ws
    - port: 4547
      targetPort: 4547
      protocol: TCP
      name: graphql
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  loadBalancerIP: 172.18.255.202
